[General.snapshot]
avro_data_file = 'data/curated/'
avro_schema_path = 'avro_schemas/'

[Deparment.snapshot]

avro_file_name = 'Deparment'
avro_schema_file = 'department.avsc'

[Job.snapshot]

avro_file_name = 'Job'
avro_schema_file = 'job.avsc'

[Hired_Employee.snapshot]

avro_file_name = 'Hired_Employee'
avro_schema_file = 'hired_employee.avsc'

[SQL.count_by_job_deparment]

template_file = "count_by_job_deparment.sql"
template_path = 'src/template/sql/'

[SQL.count_by_job_deparment.parameters]

select_year = 2021
